spring:
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
springdoc:
  swagger-ui:
    path: /application/swagger-ui.html
  api-docs:
    path: /application/api-docs

applicationLink: http://192.168.99.100:8090/deal/application
offersLink: http://192.168.99.100:8090/deal/offer

server:
  port: 8070
  error:
    include-message: always

logging:
  level:
    root: INFO
    ru.senya.application: TRACE